name: Testing

on:
- push
- pull_request

jobs:
  unit:
    name: Unit Test
    runs-on: ubuntu-18.04
    steps:
    - name: Setup Go
      id: setup-go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Build
      run: make build
    - name: Lint
      run: make lint
    - name: Test
      run: make test
  integration:
    name: Integration Test
    runs-on: ubuntu-18.04
    steps:
    - name: Setup Go
      id: setup-go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Cluster
      run: make minikube-start
    - name: Test
      run: make test-integ
